language: python

branches:
  only:
  - master
  - stable
  - /^v\d+(\.\d+)+$/

env:
  global:
    - REPO_TOOLS_BASE="https://raw.githubusercontent.com/dwhswenson/repo-tools/master"
    - CANONICAL_PYTHON="3.6"
    - TWINE_USERNAME="dwhswenson"
    - PYTHONUNBUFFERED="true"
    # TWINE_PASSWORD
    - secure: "jjXnafi5+5RaoqGZoB9Actv5yU1jk271f5fW804dcWusDwdgUSMRHyIhBNuWxmt/UggQax9rA6gq7kIvxghtugcUs1xPAsrzkQGDIP+21ebCzKgOeM0ergt9TZjMABO8rAcKoH4VrVQX8f9/CxHlAiS4D7LGLaPMrhuQgkz/jQ9HqD+KzL06kuHvqes97Q31QDvC4ihYSkZiEzRPQGoVYG1LBMRFDx9SQg06zH4cC530cj0A2gE8w9H2qa25j2kB+kYdehS4b3FUMui+tisDjnArqjvzVOlZIeiUheHQ1MqXpEFivEVK6KJrzjhlHDmJjJcJ6OsRpeCWQpPIrlF3nnFU5I7v2LcsVsHE3HAsravKPBVh12dZXYaSkllgl8lfq4yQ7N0WsE/PYR9ZDnPYRAC33hanAaRxQ+D3uBW69eCB6T2scPWLIsly2afGHnzMY2CIOL1YNmfZk+V0Y1Pj/U9XSz5e1AQG3VBOxqiaoA+87gjCxk+JcVlzkWnU4/Cs4AgX7JSesCOA2Hj5vlTDMG7Zw7blct9i3TiWJpI2CNZn+mmc16zOvKaEydJRGKNntmnTPxMxg4TjUtqtHBIrYVOjw/f6cLuH7OoI0qqRq35bIgafmNnlEHwotVYjsLwG1R+NkhObfV/+1ZjZMri0giSv4k3p3lgYB824rrADDfc="
    # AUTORELEASE_TOKEN
    - secure: "Gi+qIFrivC9eYrULnmIS3JsS5sF5nIF9ivFpv0fOV/Aw+571eI5XUZ/5RDrPZ0wmLO6S7yvohO/6WkLBdaH2RTUiRCTbhKN0MFAjowr5R/T88zmW7b/bRdW3zWEVyOxbUlVI6lJKlq7dJEM/dVgdFqqDOhfo0LUb/w82FbOrsNWTl+17PAXOtoE+4v0Y6oAeRuECCa0HptfcAtJGeURuRWNAtu3v6B82C96yevdvJvbi60IFTnQjNTHSfcCjpk4F3pCpVduMashuGhn2fCWKwM2+Yh/aspo0Lk4W8EqKgGcSGkFreKVWOv/vKwbqrDBE/5Wc27Z9qU21G0Q4jd1otxSmlrpapWTDBXLDiTykQXj8CmIOBsnSPiBUka7n7VnJXfHNyWEnPGESycofTe/88qiJmFIqq/rDY5lNveeImYZOAxf5+g0PBQQc8zhlfsDRUMVbch+TeMVslrodoGPGgDGZvb9NMm70yT2VYdqiW/maqLw8kkgMoK6Tnth1pkBHnpd8NB4O1m6ziHL1/HutNtYVRdCGFQgojJRCFhf/kALQZv267EOkvfjYpCfxpGkehZpNx2tentMXnqncDnr9VKDStmd4Q9Db6bOzlt3CsGOTvP6ROPQFEr7l+vF0VfzJts4l091m6MlEH/7zYUnSCJhe0khAS3/ZP0KnCR48ELc="
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.5
    - CONDA_PY=3.6


# we use before_install to set up the 
before_install:
  - deactivate
  - git fetch --tags
  - wget $REPO_TOOLS_BASE/install_miniconda.sh && source install_miniconda.sh
  - conda config --add channels http://conda.anaconda.org/omnia
  - conda config --add channels http://conda.anaconda.org/conda-forge

install:
  - conda install -y --file requirements.txt
  - CONTACT_MAP_BRANCH="concurrence" ./ci/contact_map_dev_install.sh
  - pip install -e .
  - pip install -r requirements-tests.txt
  - pip list

script:
  - export MPLBACKEND=PS
  - python -c "import binding_md"
  #- python autorelease_check.py --branch ${TRAVIS_BRANCH} --event ${TRAVIS_EVENT_TYPE}
  - py.test -vv --cov=binding_md --cov-report xml:cov.xml

after_success:
  - coveralls
  #- python-codacy-coverage -r cov.xml

#jobs:
  #include:
    #- stage: deploy testpypi
      ## This stage runs when you make a PR to stable. It tests that the
      ## deployment to testpypi works.
      #if: "(branch = stable) and (type = pull_request)"
      #python: '3.6'
      #addons:
        #apt_packages:
          #- pandoc
      #install:
        #- pip install twine
      #script: 
        #- pandoc --from=markdown --to=rst --output=README.rst README.md
        #- python setup.py sdist bdist_wheel
        #- twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      #after_success: skip
    #- stage: test testpypi
      ## This stage run when you make a PR to stable; after the package has
      ## been deployed to testpypi. It checks that the deployed package
      ## works.
      #if: "(branch = stable) and (type = pull_request)"
      #python: '3.6'
      #install:
        #- source ci/pip-install/install_requirements.sh
        #- pip install -r ci/pip-install/testing_requirements.txt
        #- pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple contact_map
      #script:
        #- cd ~
        #- python -c "import contact_map"
        #- py.test --pyargs contact_map
      #after_success: skip
    #- stage: cut release
      ## This stage runs after you merge a PR into stable. It cuts the GitHub
      ## release based on the current stable branch and the release notes
      ## from the last PR merged into stable.
      #if: "(branch = stable) and (not type in (pull_request, cron))"
      #python: '3.6'
      #install:
        #- pip install autorelease
      #script:
        #- VERSION=`python setup.py --version`
        #- PROJECT=`python setup.py --name`
        #- autorelease-release --project $PROJECT --version $VERSION --token $AUTORELEASE_TOKEN
      #after_success: skip
    #- stage: deploy pypi
      ## This stage runs when a version-labelled tag is made. It deploys the
      ## package to PyPI.
      #if: tag =~ ^v[0-9]+\.
      #addons:
        #apt_packages:
          #- pandoc
      #install: skip
      #script:
          #- pandoc --from=markdown --to=rst --output=README.rst README.md
      #after_success: true
      #deploy:
        #provider: pypi
        #distributions: sdist bdist_wheel
        #skip_cleanup: true  # need the readme.rst from the script stage
        #user: dwhswenson
        #on:
            #tags: true
        #password:
          #secure: "UN99BfNgMlE1qOwkbvJYMEdPGVF02dnZ5iF9HZY5HwJr7nlW1ixEGn6SzICS7WwLzthfqpbwXaqVGEsbsn1YwsvQe72JyCZxftoxZC2bVi5JV/OZka5uUTx0NXtzukZp33AUTDA9J2vushIxZCHSJG+GFqx4c+L8Y194V0QS4sw/lbtGC3qZ8jmszCnRgfPbb0tmCe4Jj1snclspPXhYtXL2z9Xh4r+ImCfosBFfThtsUs6t37/Jrx1srmDrt0eaGGBm1NAcyIVP6x03TdVVUFt/ud3U7+o0iHhqdEZKfUc2Dp6YN08Ck6Zyr/dR/A0Sc3/pWvytXwXLzOj+d7BtaAmPApcAc6v5GEmwWc4mkdsD+CEEW1q3CEFbWq6RTL+oa2zvEO6k0VrnHMCni3KqsWGmF6B209tHhy8jFAmCIruD2foUz7NxEKWNEOR4bqIjOGGIgGp4mfH+1l73JrI995ZmB1PqiIkxVeX0nPrZUZtBxOUyxg6aiL+NHMaYr5NCq2uCzDYhtwWnk26Oq6/JAEMxN+SCiC+O+DSvdQaUgUp6eS5whHGvf27ZxRMkmTSYTIMN6V1/PQ9WWSFsy0QBUYB7UJf/JLFnTi5xHj08jFNzUVOmeyq9MBzJF/ztnTTBSJgzNDROV+2qsZC0Ulm/hesMe0Swxqu/S5PelzrgwCA="
